### ISSUE TITLE
deviceorientation event is not triggering

### ISSUE THREAD

**Issue by sincraianul** [driftyco/ionic-starter-cardboard#4]
Trying to run the app on Android, but I can't get the 'deviceorientation' event to trigger, so I can't control the camera with the movement of the device. It falls back to OrbitControl. :( Doesn't even work in Chrome. Tried serving the app over http, still nothing.

**Comment by sincraianul** [comment]
Found this: https://code.google.com/p/chromium/issues/detail?id=540629

Looks like it's an issue with Android 6.0. From the thread:

> The reason is that Android M does not expose a working ROTATION_VECTOR sensor

**Comment by mlynch** [comment]
Hey @sincraianul, not sure about this one, but you might want to try the `orientationchange` event instead if you're running in Cordova. More info: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=cordova%20orientationchange
