### ISSUE TITLE
How to use 360° video inside this starter?

### ISSUE THREAD

**Issue by mladenp** [driftyco/ionic-starter-cardboard#6]
I want to use 360° video inside this cardboard starter but i couldn't figure how to include it, there isn't really any documentation.

**Comment by filoxo** [comment]
Seeing as how this starter uses threejs, you could use the [three.js video panorama](http://threejs.org/examples/?q=video#webgl_video_panorama_equirectangular) example.

**Comment by mladenp** [comment]
Yes, the only problem is that **video** doesn't work on iOS because of some Apple WebView bug so i had to use some native solutions.
I don't know why i couldn't read that anywhere and had to figure out myself. 

I later saw Aframe.io and it also doesn't mention anywhere that video doesn't work on iOS. 
They are of course also using three.js and even if they used something else i don't think they could find a solution for this problem that Apple refuses to fix.
